theme: jekyll-theme-minimal

integration_spreadsheet_key: 2PACX-1vSeOcL6TD7aibaMDNIyxIWV--3NaSQlb7hFXxxQ18c4RbCTcBRN0KbwTvUju1Wo4hXz6ysFe4GGYIQa

github_user: 839-Studio
github_repo: Novel-Coronavirus-Updates
